# Generated by Django 4.1.1 on 2022-10-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.IntegerField(null=True)),
                ('nama', models.CharField(max_length=50)),
                ('tl', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fakultas', models.CharField(max_length=50)),
                ('prodi', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIM', models.IntegerField(null=True)),
                ('nama', models.CharField(max_length=50)),
                ('tl', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fakultas', models.CharField(max_length=50)),
                ('prodi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.IntegerField(null=True)),
                ('nama', models.CharField(max_length=50)),
                ('tl', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
            ],
        ),
    ]
